project:
  type: website

website:
  title: "CabbageMees"
  favicon: images/logo.png
  twitter-card: true
  site-url: https://cabbagemees.nl
  open-graph: true
  google-analytics: G-9GMDP6RW3B
  navbar:
    logo: images/logo.png
    right:
      - about.md
      - icon: github
        href: https://github.com/Mees-Molenaar
      - icon: twitter
        href: https://twitter.com/CabbageMees
format:
  html:
    theme: pulse
    css: styles.css
